<a href="https://colab.research.google.com/github/nrutyadoshi/NLP/blob/Classwork/SVD_LDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
files = files.upload()

Saving Womens Clothing E-Commerce Reviews.csv to Womens Clothing E-Commerce Reviews.csv


In [0]:
import pandas as pd
import numpy as np

In [0]:
clothes = pd.read_csv("Womens Clothing E-Commerce Reviews.csv")

In [4]:
clothes.shape

(23486, 11)

In [5]:
clothes.head()

Unnamed: 0  Clothing ID  Age  ...   Division Name Department Name  Class Name
0           0          767   33  ...       Initmates        Intimate   Intimates
1           1         1080   34  ...         General         Dresses     Dresses
2           2         1077   60  ...         General         Dresses     Dresses
3           3         1049   50  ...  General Petite         Bottoms       Pants
4           4          847   47  ...         General            Tops     Blouses

[5 rows x 11 columns]

In [0]:
clothes.drop("Unnamed: 0",1,inplace=True)

In [0]:
clothes.fillna(" ",inplace = True)

In [0]:
clothes['Text'] = clothes['Title'].str.cat(clothes['Review Text'], sep =" ") 

In [0]:
clothes.drop(["Title", "Review Text"],1, inplace=True)

In [0]:
clothes.drop(["Recommended IND"],1, inplace=True)

In [0]:
division = pd.get_dummies(clothes["Division Name"])
department = pd.get_dummies(clothes["Department Name"])
class_ = pd.get_dummies(clothes["Class Name"])

In [0]:
division.drop([" "],1, inplace=True)
department.drop([" "],1, inplace=True)
class_.drop([" "],1, inplace=True)

In [0]:
data = pd.concat([clothes, division, department, class_],1)

In [0]:
data.drop(["Division Name", "Department Name", "Class Name"],1, inplace = True)

In [15]:
data.head()

Clothing ID  Age  Rating  ...  Sweaters Swim  Trend
0          767   33       4  ...         0    0      0
1         1080   34       5  ...         0    0      0
2         1077   60       3  ...         0    0      0
3         1049   50       5  ...         0    0      0
4          847   47       5  ...         0    0      0

[5 rows x 34 columns]

In [16]:
data.columns

Index(['Clothing ID', 'Age', 'Rating', 'Positive Feedback Count', 'Text',
       'General', 'General Petite', 'Initmates', 'Bottoms', 'Dresses',
       'Intimate', 'Jackets', 'Tops', 'Trend', 'Blouses', 'Casual bottoms',
       'Chemises', 'Dresses', 'Fine gauge', 'Intimates', 'Jackets', 'Jeans',
       'Knits', 'Layering', 'Legwear', 'Lounge', 'Outerwear', 'Pants',
       'Shorts', 'Skirts', 'Sleep', 'Sweaters', 'Swim', 'Trend'],
      dtype='object')

In [17]:
import nltk
nltk.download("all")

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading packag

True

In [0]:
import re

In [0]:
def text_data(str):
  str_new = " ".join(re.findall("[a-zA-Z]+", str))
  return (str_new)

In [0]:
data["Text"] = data.apply(lambda row: text_data(row.Text),axis=1)

In [0]:
def tokenize(str_new):
  tokens = []
  tokens = nltk.word_tokenize(str_new)
  return (tokens)

In [0]:
data["Text"] = data.apply(lambda row: tokenize(row.Text),axis=1)

In [0]:
from nltk.corpus import stopwords

In [0]:
def remove(tokens):
  removed = []
  stopword = stopwords.words('english') 
  punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
  for w in tokens:
    if (w.lower() not in stopword and w.lower() not in punctuations):
      removed.append(w.lower())
  return (removed)

In [0]:
data["Text"] = data.apply(lambda row: remove(row.Text),axis=1)

In [0]:
def tagging(removed):
  pos = []
  pos.append(nltk.pos_tag(removed))
  return (pos)

In [0]:
data["Text"] = data.apply(lambda row: tagging(row.Text),axis=1)

In [0]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

In [0]:
def lemmatization(pos):
  lem = WordNetLemmatizer()
  lemma = []
  for word in pos:
    for w in word:
      pos_value = ""
      if (w[1].startswith('J')):
        pos_value = wordnet.ADJ
      elif (w[1].startswith('V')):
        pos_value = wordnet.VERB
      elif (w[1].startswith('N')):
        pos_value = wordnet.NOUN
      elif (w[1].startswith('R')):
        pos_value = wordnet.ADV 
      else:
        continue
      lemma.append(lem.lemmatize(w[0],pos_value))
  return (lemma)

In [0]:
data["Text"] = data.apply(lambda row: lemmatization(row.Text),axis=1)

In [31]:
data.head()

Clothing ID  Age  Rating  ...  Sweaters Swim  Trend
0          767   33       4  ...         0    0      0
1         1080   34       5  ...         0    0      0
2         1077   60       3  ...         0    0      0
3         1049   50       5  ...         0    0      0
4          847   47       5  ...         0    0      0

[5 rows x 34 columns]

In [0]:
def to_string(lemma):
  str1 = ' '.join([elem for elem in lemma]) 
  return (str1)

In [0]:
data["Text"] = data.apply(lambda row: to_string(row.Text),axis=1)

In [34]:
data.head()

Clothing ID  Age  Rating  ...  Sweaters Swim  Trend
0          767   33       4  ...         0    0      0
1         1080   34       5  ...         0    0      0
2         1077   60       3  ...         0    0      0
3         1049   50       5  ...         0    0      0
4          847   47       5  ...         0    0      0

[5 rows x 34 columns]

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer 

In [0]:
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(data.Text)
feature_names = vectorizer.get_feature_names()
dense = vectors.todense()
denselist = dense.tolist()
df = pd.DataFrame(denselist, columns=feature_names)

In [38]:
df.head()

aa  aaaaaaamazing  aaaaandidon  aaaaannnnnnd  ...  zone  zoolander  zoom  zowie
0  0.0            0.0          0.0           0.0  ...   0.0        0.0   0.0    0.0
1  0.0            0.0          0.0           0.0  ...   0.0        0.0   0.0    0.0
2  0.0            0.0          0.0           0.0  ...   0.0        0.0   0.0    0.0
3  0.0            0.0          0.0           0.0  ...   0.0        0.0   0.0    0.0
4  0.0            0.0          0.0           0.0  ...   0.0        0.0   0.0    0.0

[5 rows x 11744 columns]

In [0]:
data = pd.concat([data,df],1)

In [40]:
data.head()

Clothing ID  Age  Rating  ...  zoolander zoom  zowie
0          767   33       4  ...        0.0  0.0    0.0
1         1080   34       5  ...        0.0  0.0    0.0
2         1077   60       3  ...        0.0  0.0    0.0
3         1049   50       5  ...        0.0  0.0    0.0
4          847   47       5  ...        0.0  0.0    0.0

[5 rows x 11778 columns]

In [41]:
data.shape

(23486, 11778)

In [0]:
data.drop(["Text"],1,inplace=True)

In [0]:
data.drop(["Clothing ID"],1,inplace=True)

In [44]:
data.head()

Age  Rating  Positive Feedback Count  General  ...  zone  zoolander  zoom  zowie
0   33       4                        0        0  ...   0.0        0.0   0.0    0.0
1   34       5                        4        1  ...   0.0        0.0   0.0    0.0
2   60       3                        0        1  ...   0.0        0.0   0.0    0.0
3   50       5                        0        0  ...   0.0        0.0   0.0    0.0
4   47       5                        6        1  ...   0.0        0.0   0.0    0.0

[5 rows x 11776 columns]

In [0]:
from sklearn.decomposition import NMF as nmf

In [0]:
nmf_a = nmf(n_components = 4, random_state = 42, alpha = 0.1, l1_ratio = 0.5)

In [47]:
nmf_a.fit_transform(data)

array([[0.39510336, 0.        , 0.07033043, 0.04173151],
       [0.40372643, 0.11962846, 0.01564458, 0.23439173],
       [0.717397  , 0.        , 0.        , 0.17004905],
       ...,
       [0.36910402, 0.02984194, 0.        , 0.17110098],
       [0.33303341, 0.05981957, 0.        , 0.17154563],
       [0.61821397, 0.65817578, 0.00625973, 0.25404593]])

In [48]:
nmf_a.components_

array([[8.32870696e+01, 0.00000000e+00, 3.50469678e-03, ...,
        0.00000000e+00, 8.09618795e-05, 1.99037119e-05],
       [1.99488921e-01, 0.00000000e+00, 3.34180928e+01, ...,
        8.28547922e-05, 2.77894313e-04, 0.00000000e+00],
       [3.92912057e-01, 4.41853563e+01, 0.00000000e+00, ...,
        0.00000000e+00, 8.46558175e-06, 0.00000000e+00],
       [1.47496025e+00, 1.83666657e+01, 2.87812067e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [0]:
from sklearn.decomposition import LatentDirichletAllocation

In [0]:
lda=LatentDirichletAllocation(n_components=10)

In [0]:
model_lda=lda.fit_transform(data)

In [59]:
lda.components_

array([[8.82663473e+05, 8.54919038e+04, 5.99642880e+03, ...,
        1.00102442e-01, 2.13257835e+00, 5.67850212e-01],
       [1.00000018e-01, 1.00000019e-01, 1.00000017e-01, ...,
        1.00000086e-01, 1.00000032e-01, 1.00000106e-01],
       [1.00000018e-01, 1.00000019e-01, 1.00000017e-01, ...,
        1.00000086e-01, 1.00000032e-01, 1.00000106e-01],
       ...,
       [1.31742283e+05, 1.30432862e+04, 9.80540998e+02, ...,
        4.02011522e-01, 1.00093613e-01, 1.00649896e-01],
       [1.55543423e+02, 1.31100220e+01, 5.25823302e+04, ...,
        1.00857436e-01, 1.00083620e-01, 1.00000002e-01],
       [1.00000018e-01, 1.00000019e-01, 1.00000017e-01, ...,
        1.00000086e-01, 1.00000032e-01, 1.00000106e-01]])